"""Declarative scenario definitions for scripts/run_permission_scenarios.py."""

from __future__ import annotations

DEFAULT_UX_THRESHOLDS = {
    "max_steps": 8,
    "max_user_taps": 5,
    "max_settings_hops": 1,
    "max_duration_seconds": 30,
    "max_back_presses": 2,
    "fail_on_manual_intervention": True,
}

DEFAULT_ASSISTANT_BLOCKER = (
    "Jandal is not configured as the Android default assistant; configure it manually before "
    "running Hey Jandal voice scenarios."
)
WAKE_WORD_MODEL_BLOCKER = (
    "Wake word model is not available on this build; Hey Jandal voice scenarios cannot run yet."
)
HEY_JANDAL_LABEL = 'Listen for "Hey Jandal"'

# Fixtures: deterministic values shared across scenarios.
# Scenarios reference these via their `fixtures` field for overrides.
FIXTURES: dict[str, object] = {
    "weather_named_location": "Tokyo",
    "short_timer_seconds": 10,
    "short_alarm_minutes": 1,
}

SCENARIOS: list[dict[str, object]] = [
    {
        "id": "hey_jandal_preflight",
        "title": "Hey Jandal preflight checks default assistant setup",
        "capability": "wake_word",
        "tags": ["permissions", "microphone", "wake_word", "preflight", "voice"],
        "preconditions": [],
        "cleanup": [],
        "fixtures": {},
        "steps": [
            {
                "id": "launch_app",
                "action": "launch_main",
                "expected": "Kernel AI app returns to foreground",
                "screenshot": True,
            },
            {
                "id": "open_settings",
                "action": "tap_visible",
                "target": {"content_desc": "Settings"},
                "expected": "Settings screen opens",
                "expected_visible": ["Settings"],
                "screenshot": True,
            },
            {
                "id": "open_voice_settings",
                "action": "tap_visible",
                "target": {"text": "Voice"},
                "expected": "Voice settings opens",
                "expected_visible": ["Hey Jandal", HEY_JANDAL_LABEL],
                "expected_any_visible": [
                    "Jandal is your default assistant",
                    "Set Jandal as default assistant",
                ],
                "blocked_if_visible": {
                    "texts": ["Wake word model not yet available"],
                    "reason": WAKE_WORD_MODEL_BLOCKER,
                },
                "screenshot": True,
            },
            {
                "id": "check_default_assistant_ready",
                "action": "check_default_assistant_ready",
                "expected": "Jandal default-assistant prerequisite is satisfied",
                "screenshot": True,
            },
        ],
    },
    {
        "id": "hey_jandal_enable_mic_granted",
        "title": "Enable Hey Jandal with microphone already granted",
        "capability": "wake_word",
        "tags": ["permissions", "microphone", "wake_word", "voice"],
        "preconditions": [],
        "cleanup": [],
        "fixtures": {},
        "steps": [
            {
                "id": "grant_microphone",
                "action": "set_permission_state",
                "permission": "android.permission.RECORD_AUDIO",
                "state": "granted",
                "expected": "Microphone permission granted",
            },
            {
                "id": "launch_app",
                "action": "launch_main",
                "expected": "Kernel AI app returns to foreground",
                "screenshot": True,
            },
            {
                "id": "open_settings",
                "action": "tap_visible",
                "target": {"content_desc": "Settings"},
                "expected": "Settings screen opens",
                "expected_visible": ["Settings"],
            },
            {
                "id": "open_voice_settings",
                "action": "tap_visible",
                "target": {"text": "Voice"},
                "expected": "Voice settings opens",
                "expected_visible": ["Hey Jandal", HEY_JANDAL_LABEL],
                "blocked_if_visible": {
                    "texts": ["Wake word model not yet available"],
                    "reason": WAKE_WORD_MODEL_BLOCKER,
                },
                "screenshot": True,
            },
            {
                "id": "check_default_assistant_ready",
                "action": "check_default_assistant_ready",
                "expected": "Jandal default-assistant prerequisite is satisfied",
            },
            {
                "id": "reset_hey_jandal_toggle_off",
                "action": "set_toggle_state",
                "anchor_text": HEY_JANDAL_LABEL,
                "checked": False,
                "expected": "Hey Jandal toggle is reset to off before enablement",
                "expected_toggle_state": {"anchor_text": HEY_JANDAL_LABEL, "checked": False},
            },
            {
                "id": "enable_hey_jandal_toggle",
                "action": "set_toggle_state",
                "anchor_text": HEY_JANDAL_LABEL,
                "checked": True,
                "expected": "Hey Jandal toggle is enabled",
                "expected_toggle_state": {"anchor_text": HEY_JANDAL_LABEL, "checked": True},
                "screenshot": True,
            },
        ],
    },
    {
        "id": "hey_jandal_enable_mic_denied",
        "title": "Enable Hey Jandal with microphone promptable denied",
        "capability": "wake_word",
        "tags": ["permissions", "microphone", "wake_word", "voice"],
        "preconditions": [],
        "cleanup": [],
        "fixtures": {},
        "steps": [
            {
                "id": "grant_microphone_for_toggle_reset",
                "action": "set_permission_state",
                "permission": "android.permission.RECORD_AUDIO",
                "state": "granted",
                "expected": "Microphone permission granted so the Hey Jandal toggle can be reset safely",
            },
            {
                "id": "launch_app",
                "action": "launch_main",
                "expected": "Kernel AI app returns to foreground",
                "screenshot": True,
            },
            {
                "id": "open_settings",
                "action": "tap_visible",
                "target": {"content_desc": "Settings"},
                "expected": "Settings screen opens",
                "expected_visible": ["Settings"],
            },
            {
                "id": "open_voice_settings",
                "action": "tap_visible",
                "target": {"text": "Voice"},
                "expected": "Voice settings opens",
                "expected_visible": ["Hey Jandal", HEY_JANDAL_LABEL],
                "blocked_if_visible": {
                    "texts": ["Wake word model not yet available"],
                    "reason": WAKE_WORD_MODEL_BLOCKER,
                },
                "screenshot": True,
            },
            {
                "id": "check_default_assistant_ready",
                "action": "check_default_assistant_ready",
                "expected": "Jandal default-assistant prerequisite is satisfied",
            },
            {
                "id": "reset_hey_jandal_toggle_off",
                "action": "set_toggle_state",
                "anchor_text": HEY_JANDAL_LABEL,
                "checked": False,
                "expected": "Hey Jandal toggle is reset to off before microphone permission prompting",
                "expected_toggle_state": {"anchor_text": HEY_JANDAL_LABEL, "checked": False},
            },
            {
                "id": "reset_microphone_prompt_state",
                "action": "set_permission_state",
                "permission": "android.permission.RECORD_AUDIO",
                "state": "prompt",
                "expected": "Microphone permission reset to promptable denied state",
            },
            {
                "id": "relaunch_app_after_permission_reset",
                "action": "launch_main",
                "expected": "Kernel AI app returns to foreground after microphone permission reset",
            },
            {
                "id": "reopen_settings_after_permission_reset",
                "action": "tap_visible",
                "target": {"content_desc": "Settings"},
                "expected": "Settings screen reopens after microphone permission reset",
                "expected_visible": ["Settings"],
            },
            {
                "id": "reopen_voice_settings_after_permission_reset",
                "action": "tap_visible",
                "target": {"text": "Voice"},
                "expected": "Voice settings reopen after microphone permission reset",
                "expected_visible": ["Hey Jandal", HEY_JANDAL_LABEL],
                "blocked_if_visible": {
                    "texts": ["Wake word model not yet available"],
                    "reason": WAKE_WORD_MODEL_BLOCKER,
                },
            },
            {
                "id": "recheck_default_assistant_ready",
                "action": "check_default_assistant_ready",
                "expected": "Jandal default-assistant prerequisite remains satisfied after microphone permission reset",
            },
            {
                "id": "request_microphone_via_toggle",
                "action": "tap_toggle_for_text",
                "anchor_text": HEY_JANDAL_LABEL,
                "expected": "Android microphone permission prompt appears",
                "expected_any_visible": ["Allow", "While using the app", "Only this time", "Don't allow", "Deny"],
                "screenshot": True,
            },
            {
                "id": "deny_microphone_prompt",
                "action": "tap_visible",
                "target": {"any_text": ["Don't allow", "Deny", "No thanks", "Cancel"]},
                "expected": "Permission prompt is denied and app remains usable",
                "expected_visible": [HEY_JANDAL_LABEL],
                "expected_toggle_state": {"anchor_text": HEY_JANDAL_LABEL, "checked": False},
                "expected_not_visible": ["Microphone permission is blocked", "Microphone access was removed"],
                "screenshot": True,
            },
        ],
    },
    {
        "id": "hey_jandal_mic_revoked_reopen_voice",
        "title": "Revoke microphone externally and reopen Voice to verify durability repair UX",
        "capability": "wake_word",
        "tags": ["permissions", "microphone", "wake_word", "voice", "durability"],
        "preconditions": [],
        "cleanup": [],
        "fixtures": {},
        "steps": [
            {
                "id": "grant_microphone",
                "action": "set_permission_state",
                "permission": "android.permission.RECORD_AUDIO",
                "state": "granted",
                "expected": "Microphone permission granted so Hey Jandal can be enabled",
            },
            {
                "id": "launch_app",
                "action": "launch_main",
                "expected": "Kernel AI app returns to foreground",
                "screenshot": True,
            },
            {
                "id": "open_settings",
                "action": "tap_visible",
                "target": {"content_desc": "Settings"},
                "expected": "Settings screen opens",
                "expected_visible": ["Settings"],
            },
            {
                "id": "open_voice_settings",
                "action": "tap_visible",
                "target": {"text": "Voice"},
                "expected": "Voice settings opens",
                "expected_visible": ["Hey Jandal", HEY_JANDAL_LABEL],
                "blocked_if_visible": {
                    "texts": ["Wake word model not yet available"],
                    "reason": WAKE_WORD_MODEL_BLOCKER,
                },
                "screenshot": True,
            },
            {
                "id": "check_default_assistant_ready",
                "action": "check_default_assistant_ready",
                "expected": "Jandal default-assistant prerequisite is satisfied",
            },
            {
                "id": "reset_hey_jandal_toggle_off",
                "action": "set_toggle_state",
                "anchor_text": HEY_JANDAL_LABEL,
                "checked": False,
                "expected": "Hey Jandal toggle is reset to off before enablement",
                "expected_toggle_state": {"anchor_text": HEY_JANDAL_LABEL, "checked": False},
            },
            {
                "id": "enable_hey_jandal_toggle",
                "action": "set_toggle_state",
                "anchor_text": HEY_JANDAL_LABEL,
                "checked": True,
                "expected": "Hey Jandal toggle is enabled and wake word is active",
                "expected_toggle_state": {"anchor_text": HEY_JANDAL_LABEL, "checked": True},
                "screenshot": True,
            },
            {
                "id": "background_app_before_revoke",
                "action": "press_home",
                "expected": "Background the app before external revoke to avoid lock screen interference on Samsung",
            },
            {
                "id": "revoke_microphone_externally",
                "action": "set_permission_state",
                "permission": "android.permission.RECORD_AUDIO",
                "state": "revoked",
                "expected": "Microphone permission revoked externally while app was backgrounded",
            },
            {
                "id": "relaunch_and_assert_durability",
                "action": "launch_main",
                "expected": "App relaunched; NavController restores Voice backstack, DataStore loads heyJandalEnabled=true, LaunchedEffect triggers durability dialog",
                "expected_visible": [
                    "Microphone access was removed",
                    "Open Microphone permission settings",
                ],
                "screenshot": True,
            },
        ],
    },
    {
        "id": "weather_location_denied",
        "title": "Weather request with location denied uses fallback UX",
        "capability": "weather_current_location",
        "tags": ["permissions", "location", "weather"],
        "preconditions": [],
        "cleanup": [
            {"id": "reset_location_after_test", "action": "set_permission_state", "permission": "android.permission.ACCESS_COARSE_LOCATION", "state": "prompt", "also_apply": ["android.permission.ACCESS_FINE_LOCATION"], "expected": "Location permissions reset to prompt state after test"},
        ],
        "fixtures": {},
        "steps": [
            {
                "id": "reset_location_prompt_state",
                "action": "set_permission_state",
                "permission": "android.permission.ACCESS_COARSE_LOCATION",
                "state": "prompt",
                "also_apply": ["android.permission.ACCESS_FINE_LOCATION"],
                "expected": "Location permissions reset to promptable denied state",
            },
            {
                "id": "launch_weather_query",
                "action": "launch_quick_action",
                "query": "what's the weather",
                "expected": "Weather permission dialog appears",
                "expected_visible": ["Use your location for local weather?", "Use my location", "Use a named location"],
                "screenshot": True,
            },
            {
                "id": "choose_named_location",
                "action": "tap_visible",
                "target": {"text": "Use a named location"},
                "expected": "Fallback guidance appears instead of forcing location access",
                "expected_visible": ['Type a place name in the quick command bar, like "weather in Tokyo".'],
                "screenshot": True,
            },
        ],
    },
    {
        "id": "weather_location_granted",
        "title": "Weather with location granted does not trigger current-location permission prompt",
        "capability": "weather_current_location",
        "tags": ["permissions", "location", "weather"],
        "preconditions": [],
        "cleanup": [
            {"id": "reset_location_after_granted", "action": "set_permission_state", "permission": "android.permission.ACCESS_COARSE_LOCATION", "state": "prompt", "also_apply": ["android.permission.ACCESS_FINE_LOCATION"], "expected": "Location permissions reset to prompt state after granted scenario"},
        ],
        "fixtures": {},
        "steps": [
            {
                "id": "grant_coarse_location",
                "action": "set_permission_state",
                "permission": "android.permission.ACCESS_COARSE_LOCATION",
                "state": "granted",
                "also_apply": ["android.permission.ACCESS_FINE_LOCATION"],
                "expected": "Both coarse and fine location permissions granted",
            },
            {
                "id": "launch_weather_with_location",
                "action": "launch_quick_action",
                "query": "what's the weather",
                "expected": "Weather query launched without showing current-location permission prompt or blocked copy",
                "expected_not_visible": [
                    "Use your location for local weather?",
                    "Location permission is blocked",
                ],
                "screenshot": True,
            },
        ],
    },
    {
        "id": "weather_location_prompt_denied",
        "title": "Weather request denied at system permission prompt shows fallback gracefully",
        "capability": "weather_current_location",
        "tags": ["permissions", "location", "weather"],
        "preconditions": [],
        "cleanup": [
            {"id": "reset_location_after_prompt_denied", "action": "set_permission_state", "permission": "android.permission.ACCESS_COARSE_LOCATION", "state": "prompt", "also_apply": ["android.permission.ACCESS_FINE_LOCATION"], "expected": "Location permissions reset to prompt state after prompt-denied scenario"},
        ],
        "fixtures": {},
        "steps": [
            {
                "id": "reset_location_to_prompt",
                "action": "set_permission_state",
                "permission": "android.permission.ACCESS_COARSE_LOCATION",
                "state": "prompt",
                "also_apply": ["android.permission.ACCESS_FINE_LOCATION"],
                "expected": "Location permissions reset to promptable denied state",
            },
            {
                "id": "launch_weather_from_prompt_denied",
                "action": "launch_quick_action",
                "query": "what's the weather",
                "expected": "Jandal shows permission-request dialog for location",
                "expected_visible": ["Use your location for local weather?", "Use my location", "Use a named location"],
                "screenshot": True,
            },
            {
                "id": "trigger_location_system_prompt",
                "action": "tap_visible",
                "target": {"text": "Use my location"},
                "expected": "Android system location permission prompt appears",
                "expected_any_visible": ["Allow", "While using the app", "Only this time", "Don't allow", "Deny"],
                "screenshot": True,
            },
            {
                "id": "deny_location_system_prompt",
                "action": "tap_visible",
                "target": {"any_text": ["Don't allow", "Deny"]},
                "expected": "System prompt denied and app returns to chat without crash",
                "expected_not_visible": ["Allow", "Deny", "Don't allow"],
                "screenshot": True,
            },
        ],
    },
    {
        "id": "weather_location_blocked_or_permanently_denied",
        "title": "Weather with location permanently blocked shows blocked or standard permission dialog",
        "capability": "weather_current_location",
        "tags": ["permissions", "location", "weather"],
        "preconditions": [],
        "cleanup": [
            {"id": "unblock_location_after_test", "action": "set_permission_state", "permission": "android.permission.ACCESS_COARSE_LOCATION", "state": "prompt", "also_apply": ["android.permission.ACCESS_FINE_LOCATION"], "expected": "Location permissions reset from blocked to prompt state after test"},
        ],
        "fixtures": {},
        "steps": [
            {
                "id": "set_location_to_blocked",
                "action": "set_permission_state",
                "permission": "android.permission.ACCESS_COARSE_LOCATION",
                "state": "blocked",
                "also_apply": ["android.permission.ACCESS_FINE_LOCATION"],
                "expected": "Location permissions set to blocked (user-set, user-fixed) simulating permanent denial",
            },
            {
                "id": "launch_weather_while_blocked",
                "action": "launch_quick_action",
                "query": "what's the weather",
                "expected": "Jandal detects location is unavailable and shows a dialog (blocked repair copy or standard permission request)",
                "expected_any_visible": [
                    "Location permission is blocked",
                    "Open Location permission settings",
                    "Use your location for local weather?",
                    "Use my location",
                ],
                "screenshot": True,
            },
        ],
    },
    {
        "id": "weather_typed_city_without_location",
        "title": "Named city weather query does not trigger current-location permission prompt",
        "capability": "weather_current_location",
        "tags": ["permissions", "location", "weather"],
        "preconditions": [],
        "cleanup": [
            {"id": "reset_location_after_typed_city", "action": "set_permission_state", "permission": "android.permission.ACCESS_COARSE_LOCATION", "state": "prompt", "also_apply": ["android.permission.ACCESS_FINE_LOCATION"], "expected": "Location permissions reset to prompt state after typed-city scenario"},
        ],
        "fixtures": {},
        "steps": [
            {
                "id": "reset_location_for_typed_city",
                "action": "set_permission_state",
                "permission": "android.permission.ACCESS_COARSE_LOCATION",
                "state": "prompt",
                "also_apply": ["android.permission.ACCESS_FINE_LOCATION"],
                "expected": "Location permissions reset to promptable denied state",
            },
            {
                "id": "launch_typed_city_weather",
                "action": "launch_quick_action",
                "query": f"weather in {FIXTURES['weather_named_location']}",
                "expected": "Named city weather query launched without showing current-location permission prompt or blocked copy",
                "expected_not_visible": [
                    "Use your location for local weather?",
                    "Location permission is blocked",
                ],
                "screenshot": True,
            },
        ],
    },
    {
        "id": "clock_timer_notifications_allowed",
        "title": "Timer set with notifications allowed succeeds",
        "capability": "jandal_alarms_timers",
        "tags": ["permissions", "notifications", "clock", "timer"],
        "preconditions": [],
        "cleanup": [
            {"id": "reset_notifications_after_timer_allowed", "action": "set_permission_state", "permission": "android.permission.POST_NOTIFICATIONS", "state": "prompt", "expected": "POST_NOTIFICATIONS reset to prompt state after timer-allowed scenario"},
        ],
        "fixtures": {},
        "steps": [
            {
                "id": "grant_notifications",
                "action": "set_permission_state",
                "permission": "android.permission.POST_NOTIFICATIONS",
                "state": "granted",
                "expected": "POST_NOTIFICATIONS permission granted",
            },
            {
                "id": "launch_short_timer",
                "action": "launch_quick_action",
                "query": f"set timer for {FIXTURES['short_timer_seconds']} seconds",
                "expected": "Short timer set successfully with notifications allowed",
                "expected_visible_contains": ["Timer set for"],
                "screenshot": True,
                "timeout_seconds": 15,
            },
        ],
    },
    {
        "id": "clock_timer_notifications_denied",
        "title": "Timer with notifications denied shows blocked or degraded message",
        "capability": "jandal_alarms_timers",
        "tags": ["permissions", "notifications", "clock", "timer"],
        "preconditions": [],
        "cleanup": [
            {"id": "restore_notifications_after_timer_denied", "action": "set_permission_state", "permission": "android.permission.POST_NOTIFICATIONS", "state": "granted", "expected": "POST_NOTIFICATIONS restored to granted after timer-denied scenario"},
        ],
        "fixtures": {},
        "steps": [
            {
                "id": "revoke_notifications",
                "action": "set_permission_state",
                "permission": "android.permission.POST_NOTIFICATIONS",
                "state": "revoked",
                "expected": "POST_NOTIFICATIONS permission revoked",
            },
            {
                "id": "launch_timer_without_notifications",
                "action": "launch_quick_action",
                "query": f"set timer for {FIXTURES['short_timer_seconds']} seconds",
                "expected": "Timer command processed; app shows either success or notification-blocked message depending on capability enforcement",
                "expected_any_visible_contains": [
                    "Timer set for",
                    "notifications",
                    "notification access",
                ],
                "screenshot": True,
                "timeout_seconds": 15,
            },
        ],
    },
    {
        "id": "clock_alarm_exact_alarm_allowed",
        "title": "Alarm with exact alarm capability allowed succeeds",
        "capability": "jandal_alarms_timers",
        "tags": ["permissions", "notifications", "exact_alarm", "clock", "alarm"],
        "preconditions": [],
        "cleanup": [
            {"id": "cancel_alarm_after_test", "action": "launch_quick_action", "query": "cancel my alarm", "expected": "Alarm cancelled as cleanup to avoid leaving persistent alarms on device", "timeout_seconds": 15},
            {"id": "reset_notifications_after_alarm_allowed", "action": "set_permission_state", "permission": "android.permission.POST_NOTIFICATIONS", "state": "prompt", "expected": "POST_NOTIFICATIONS reset after alarm-allowed scenario"},
        ],
        "steps": [
            {
                "id": "grant_notifications",
                "action": "set_permission_state",
                "permission": "android.permission.POST_NOTIFICATIONS",
                "state": "granted",
                "expected": "POST_NOTIFICATIONS permission granted",
            },
            {
                "id": "launch_set_alarm",
                "action": "launch_quick_action",
                "query": f"set alarm for 9:00 AM",
                "expected": "Alarm set successfully with exact alarm capability available",
                "expected_visible_contains": ["Alarm set for"],
                "screenshot": True,
                "timeout_seconds": 15,
            },
        ],
    },
    {
        "id": "clock_alarm_schedule_exact_alarm_appop_denied",
        "title": "Documents that SCHEDULE_EXACT_ALARM appop denial does not block alarm scheduling when USE_EXACT_ALARM is declared",
        "capability": "jandal_alarms_timers",
        "tags": ["permissions", "notifications", "exact_alarm", "clock", "alarm"],
        "preconditions": [],
        "cleanup": [
            {"id": "cancel_alarm_after_appop_denied_test", "action": "launch_quick_action", "query": "cancel my alarm", "expected": "Alarm cancelled as cleanup after SCHEDULE_EXACT_ALARM appop denial test", "timeout_seconds": 15},
            {"id": "restore_exact_alarm_after_test", "action": "set_appops", "permission": "SCHEDULE_EXACT_ALARM", "mode": "allow", "expected": "SCHEDULE_EXACT_ALARM restored to allow after appop-denied scenario"},
            {"id": "reset_notifications_after_alarm_blocked", "action": "set_permission_state", "permission": "android.permission.POST_NOTIFICATIONS", "state": "prompt", "expected": "POST_NOTIFICATIONS reset after appop-denied scenario"},
        ],
        "fixtures": {},
        "steps": [
            {
                "id": "grant_notifications",
                "action": "set_permission_state",
                "permission": "android.permission.POST_NOTIFICATIONS",
                "state": "granted",
                "expected": "POST_NOTIFICATIONS permission granted before testing appop denial",
            },
            {
                "id": "block_exact_alarm_via_appops",
                "action": "set_appops",
                "permission": "SCHEDULE_EXACT_ALARM",
                "mode": "deny",
                "expected": "SCHEDULE_EXACT_ALARM denied via appops; confirms app does not check SCHEDULE_EXACT_ALARM for alarm scheduling (uses USE_EXACT_ALARM manifest permission)",
            },
            {
                "id": "launch_alarm_while_appop_denied",
                "action": "launch_quick_action",
                "query": f"set alarm for 9:00 AM",
                "expected": "Alarm command processed; SCHEDULE_EXACT_ALARM appop denial does not block alarm scheduling when USE_EXACT_ALARM is declared",
                "expected_any_visible_contains": [
                    "Alarm set for",
                    "exact alarm",
                ],
                "screenshot": True,
                "timeout_seconds": 15,
            },
        ],
    },
    {
        "id": "permissions_dashboard_opens",
        "title": "App Permissions dashboard opens and displays expected launch-critical rows",
        "capability": "",
        "tags": ["permissions", "dashboard"],
        "preconditions": [
            {"id": "launch_app", "action": "launch_main", "expected": "App launched before dashboard navigation"},
        ],
        "steps": [
            {
                "id": "open_settings_via_top_bar",
                "action": "tap_visible",
                "target": {"content_desc": "Settings"},
                "expected": "Settings screen opened via top bar icon",
            },
            {
                "id": "scroll_settings_opens",
                "action": "swipe",
                "start_x": 540,
                "start_y": 1200,
                "end_x": 540,
                "end_y": 400,
                "duration_ms": 200,
                "expected": "Scrolled Settings screen to reveal App Permissions row",
            },
            {
                "id": "tap_app_permissions_row",
                "action": "tap_visible",
                "target": {"text": "App Permissions"},
                "expected": "Tapped App Permissions row, navigating to App Permissions dashboard",
                "expected_visible": ["App Permissions"],
                "screenshot": True,
            },
        ],
    },
    {
        "id": "permissions_dashboard_location_state_refresh",
        "title": "Location permission state refresh - revoke, open dashboard, assert denied, grant, refresh, assert granted",
        "capability": "",
        "tags": ["permissions", "dashboard", "location", "refresh"],
        "preconditions": [
            {"id": "launch_app_location_refresh", "action": "launch_main", "expected": "App launched before dashboard location refresh scenario"},
        ],
        "cleanup": [
            {"id": "restore_location_after_dashboard_location_refresh", "action": "set_permission_state", "permission": "android.permission.ACCESS_COARSE_LOCATION", "state": "prompt", "expected": "ACCESS_COARSE_LOCATION restored to prompt after dashboard location refresh scenario"},
        ],
        "fixtures": {},
        "steps": [
            {
                "id": "revoke_location",
                "action": "set_permission_state",
                "permission": "android.permission.ACCESS_COARSE_LOCATION",
                "state": "revoked",
                "expected": "ACCESS_COARSE_LOCATION revoked for dashboard location refresh test",
            },
            {
                "id": "tap_settings_icon_location",
                "action": "tap_visible",
                "target": {"content_desc": "Settings"},
                "expected": "Settings screen opened via top bar icon",
            },
            {
                "id": "scroll_settings_location",
                "action": "swipe",
                "start_x": 540,
                "start_y": 1200,
                "end_x": 540,
                "end_y": 400,
                "duration_ms": 200,
                "expected": "Scrolled Settings screen to reveal App Permissions row",
            },
            {
                "id": "tap_app_permissions_location",
                "action": "tap_visible",
                "target": {"text": "App Permissions"},
                "expected": "Tapped App Permissions row, navigating to dashboard",
                "expected_visible": ["App Permissions"],
                "screenshot": True,
            },
            {
                "id": "assert_location_denied",
                "action": "wait_for_package",
                "package": "com.kernel.ai.debug",
                "expected": "Dashboard is visible, location row shows denied state",
                "expected_visible": ["Location", "Location not granted"],
                "timeout_seconds": 8,
            },
            {
                "id": "grant_location",
                "action": "set_permission_state",
                "permission": "android.permission.ACCESS_COARSE_LOCATION",
                "state": "granted",
                "expected": "ACCESS_COARSE_LOCATION granted for dashboard location refresh test",
            },
            {
                "id": "tap_refresh",
                "action": "tap_visible",
                "target": {"text": "Refresh"},
                "expected": "Refresh button tapped, dashboard refreshes to show updated grant state",
                "expected_visible": ["Location granted"],
                "timeout_seconds": 15,
            },
        ],
    },
    {
        "id": "permissions_dashboard_microphone_state_refresh",
        "title": "Microphone permission state refresh - revoke, open dashboard, assert denied, grant, refresh, assert granted",
        "capability": "",
        "tags": ["permissions", "dashboard", "microphone", "refresh"],
        "preconditions": [
            {"id": "launch_app_mic_refresh", "action": "launch_main", "expected": "App launched before dashboard mic refresh scenario"},
        ],
        "cleanup": [
            {"id": "restore_microphone_after_dashboard_mic_refresh", "action": "set_permission_state", "permission": "android.permission.RECORD_AUDIO", "state": "prompt", "expected": "RECORD_AUDIO restored to prompt after dashboard mic refresh scenario"},
        ],
        "fixtures": {},
        "steps": [
            {
                "id": "revoke_microphone",
                "action": "set_permission_state",
                "permission": "android.permission.RECORD_AUDIO",
                "state": "revoked",
                "expected": "RECORD_AUDIO revoked for dashboard mic refresh test",
            },
            {
                "id": "tap_settings_icon_mic",
                "action": "tap_visible",
                "target": {"content_desc": "Settings"},
                "expected": "Settings screen opened via top bar icon",
            },
            {
                "id": "scroll_settings_mic",
                "action": "swipe",
                "start_x": 540,
                "start_y": 1200,
                "end_x": 540,
                "end_y": 400,
                "duration_ms": 200,
                "expected": "Scrolled Settings screen to reveal App Permissions row",
            },
            {
                "id": "tap_app_permissions_mic",
                "action": "tap_visible",
                "target": {"text": "App Permissions"},
                "expected": "Tapped App Permissions row, navigating to dashboard",
                "expected_visible": ["App Permissions"],
                "screenshot": True,
            },
            {
                "id": "assert_microphone_denied",
                "action": "wait_for_package",
                "package": "com.kernel.ai.debug",
                "expected": "Dashboard is visible, microphone row shows denied state",
                "expected_visible": ["Microphone", "Microphone not granted"],
                "timeout_seconds": 8,
            },
            {
                "id": "grant_microphone",
                "action": "set_permission_state",
                "permission": "android.permission.RECORD_AUDIO",
                "state": "granted",
                "expected": "RECORD_AUDIO granted for dashboard mic refresh test",
            },
            {
                "id": "tap_refresh_after_mic_grant",
                "action": "tap_visible",
                "target": {"text": "Refresh"},
                "expected": "Refresh button tapped, dashboard refreshes to show microphone as granted",
                "expected_visible": ["Microphone granted"],
                "timeout_seconds": 15,
            },
        ],
    },
    {
        "id": "permissions_dashboard_notification_state",
        "title": "Notification permission state visible on dashboard - revoke, open dashboard, assert denied, restore",
        "capability": "",
        "tags": ["permissions", "dashboard", "notifications", "state"],
        "preconditions": [
            {"id": "launch_app_notification_state", "action": "launch_main", "expected": "App launched before dashboard notification state scenario"},
        ],
        "cleanup": [
            {"id": "restore_notifications_after_dashboard_notification_state", "action": "set_permission_state", "permission": "android.permission.POST_NOTIFICATIONS", "state": "prompt", "expected": "POST_NOTIFICATIONS restored to prompt after dashboard notification state scenario"},
        ],
        "fixtures": {},
        "steps": [
            {
                "id": "revoke_notifications_for_dashboard",
                "action": "set_permission_state",
                "permission": "android.permission.POST_NOTIFICATIONS",
                "state": "revoked",
                "expected": "POST_NOTIFICATIONS revoked for dashboard notification state test",
            },
            {
                "id": "tap_settings_icon_notifications",
                "action": "tap_visible",
                "target": {"content_desc": "Settings"},
                "expected": "Settings screen opened via top bar icon",
            },
            {
                "id": "scroll_settings_notifications",
                "action": "swipe",
                "start_x": 540,
                "start_y": 1200,
                "end_x": 540,
                "end_y": 400,
                "duration_ms": 200,
                "expected": "Scrolled Settings screen to reveal App Permissions row",
            },
            {
                "id": "tap_app_permissions_notifications",
                "action": "tap_visible",
                "target": {"text": "App Permissions"},
                "expected": "Tapped App Permissions row, navigating to dashboard",
                "expected_visible": ["App Permissions"],
                "screenshot": True,
            },
            {
                "id": "assert_notifications_denied",
                "action": "wait_for_package",
                "package": "com.kernel.ai.debug",
                "expected": "Dashboard is visible, notifications row shows denied state",
                "expected_visible": ["Notifications", "Notifications not granted"],
                "timeout_seconds": 8,
            },
        ],
    },
    {
        "id": "permissions_dashboard_repair_cta_opens_settings",
        "title": "Repair CTA opens system App Info settings - tap denied row, assert settings opens, return to dashboard",
        "capability": "",
        "tags": ["permissions", "dashboard", "repair"],
        "preconditions": [
            {"id": "launch_app_repair_cta", "action": "launch_main", "expected": "App launched before dashboard repair CTA scenario"},
        ],
        "cleanup": [
            {"id": "restore_location_after_repair_cta", "action": "set_permission_state", "permission": "android.permission.ACCESS_COARSE_LOCATION", "state": "prompt", "expected": "ACCESS_COARSE_LOCATION restored to prompt after repair CTA scenario"},
        ],
        "fixtures": {},
        "steps": [
            {
                "id": "revoke_location_for_repair",
                "action": "set_permission_state",
                "permission": "android.permission.ACCESS_COARSE_LOCATION",
                "state": "revoked",
                "expected": "ACCESS_COARSE_LOCATION revoked for repair CTA test",
            },
            {
                "id": "tap_settings_icon_repair",
                "action": "tap_visible",
                "target": {"content_desc": "Settings"},
                "expected": "Settings screen opened via top bar icon",
            },
            {
                "id": "scroll_settings_repair",
                "action": "swipe",
                "start_x": 540,
                "start_y": 1200,
                "end_x": 540,
                "end_y": 400,
                "duration_ms": 200,
                "expected": "Scrolled Settings screen to reveal App Permissions row",
            },
            {
                "id": "tap_app_permissions_repair",
                "action": "tap_visible",
                "target": {"text": "App Permissions"},
                "expected": "Tapped App Permissions row, navigating to dashboard",
                "expected_visible": ["App Permissions"],
                "screenshot": True,
            },
            {
                "id": "navigate_to_permissions_post_return",
                "action": "tap_visible",
                "target": {"text": "App Permissions"},
                "expected": "Tapped App Permissions row, navigated back to dashboard",
                "expected_visible": ["App Permissions"],
                "screenshot": True,
            },
            {
                "id": "tap_denied_location_row",
                "action": "tap_visible",
                "target": {"text": "Location"},
                "expected": "Tapped denied Location row, triggering repair CTA to open system App Info settings",
            },
            {
                "id": "assert_settings_surface_opens",
                "action": "wait_for_package",
                "package": "com.android.settings",
                "expected": "System settings App Info page opened after tapping denied row",
                "timeout_seconds": 10,
            },
            {
                "id": "return_to_jandal",
                "action": "launch_main",
                "expected": "Returned to Jandal main screen after settings repair round-trip",
            },
            {
                "id": "go_back_to_chat_from_dashboard",
                "action": "press_back",
                "expected": "Pressed Back to leave dashboard if it restored",
            },
            {
                "id": "go_back_to_chat_from_settings",
                "action": "press_back",
                "expected": "Pressed Back to leave Settings screen if needed",
            },
            {
                "id": "open_settings_post_return",
                "action": "tap_visible",
                "target": {"content_desc": "Settings"},
                "expected": "Settings screen opened via top bar icon after returning from repair",
            },
            {
                "id": "scroll_settings_post_return",
                "action": "swipe",
                "start_x": 540,
                "start_y": 1200,
                "end_x": 540,
                "end_y": 400,
                "duration_ms": 200,
                "expected": "Scrolled to App Permissions after return",
            },
            {
                "id": "tap_permissions_post_return",
                "action": "tap_visible",
                "target": {"text": "App Permissions"},
                "expected": "Navigated back to App Permissions dashboard after round-trip",
                "expected_visible": ["App Permissions"],
            },
        ],
    },
]
