package com.kernel.ai.core.voice

import ai.onnxruntime.OrtEnvironment
import ai.onnxruntime.OrtSession
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.security.MessageDigest

/**
 * #1432 — production-vs-training feature-pipeline parity with the real
 * committed models (JVM ONNX Runtime, CPU).
 *
 * Executes the exact production Stage 1/2/3 logic used by
 * [OnnxWakeWordDetector] (the extracted internal functions the hot loop calls)
 * on the committed deterministic PCM (`parity_pcm.bin`) and compares every
 * checkpoint against the authoritative Python/openWakeWord reference
 * (`parity_reference.json`, generated by `generate_parity_reference.py` with
 * openwakeword 0.4.0 `AudioFeatures` streaming — the feature path used to
 * generate the committed fixture streams and to train the committed
 * classifier; see `wake-embeddings/PARITY.md`):
 *
 *   1. mel-model input length per chunk (1280 for chunk 1, 1760 afterwards);
 *   2. Stage-1 raw output rows (after the value/10+2 transform);
 *   3. mel-row append/drop cadence (5 rows for chunk 1, 8 rows afterwards);
 *   4. the complete 76×32 rolling mel context Stage 2 sees;
 *   5. the 96-dim Stage-2 embedding;
 *   6. the 16×96 classifier window and confidence.
 *
 * The reference pipeline is structurally different from the pre-#1432
 * production pipeline: openWakeWord streams the mel model the last
 * `n + 480` buffered samples (current chunk + the 480-sample tail of the
 * previous chunk) and appends all 8 output rows per chunk, while the old
 * production path fed exactly 1280 samples and appended only 5 rows.  This
 * test fails against that old framing (the first divergence is the
 * mel-row append cadence at chunk 2: 5 rows vs the reference 8) and passes
 * only when the production Stage-1 framing matches the reference.
 */
class WakeWordFeaturePipelineParityTest {

    private val env: OrtEnvironment = OrtEnvironment.getEnvironment()

    private fun loadSession(name: String): OrtSession {
        val bytes = checkNotNull(javaClass.getResourceAsStream("/models/wakeword/$name")) {
            "committed model $name missing from test resources"
        }.use { it.readBytes() }
        return env.createSession(bytes, OrtSession.SessionOptions())
    }

    private val melSession by lazy { loadSession("melspectrogram.onnx") }
    private val melInputName by lazy { melSession.inputNames.first() }
    private val melOutputName by lazy { melSession.outputNames.first() }

    private val embedSession by lazy { loadSession("embedding_model.onnx") }
    private val embedInputName by lazy { embedSession.inputNames.first() }
    private val embedOutputName by lazy { embedSession.outputNames.first() }

    private val classSession by lazy { loadSession("hey_jandal.onnx") }
    private val classInputName by lazy { classSession.inputNames.first() }
    private val classOutputName by lazy { classSession.outputNames.first() }

    // ── Committed artifacts ───────────────────────────────────────────────────

    private fun readResource(name: String): ByteArray =
        checkNotNull(javaClass.getResourceAsStream("/wake-embeddings/$name")).use { it.readBytes() }

    private val referenceJson: String by lazy {
        readResource("parity_reference.json").toString(Charsets.UTF_8)
    }

    private fun sha256(bytes: ByteArray): String =
        MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) }

    private val pcm: ShortArray by lazy {
        val bytes = readResource("parity_pcm.bin")
        ShortArray(bytes.size / 2) { i ->
            ((bytes[2 * i].toInt() and 0xFF) or (bytes[2 * i + 1].toInt() shl 8)).toShort()
        }
    }

    // ── Minimal parser for the generator's JSON schema ────────────────────────
    // The reference file is a flat object with scalar fields + chunk_records:
    // [{chunk, mel_input_samples, mel_rows_appended, mel_rows, mel_buffer_rows,
    //   window_rows, embedding, classifier_confidence}, ...].  Values are
    // floats (possibly null) or nested float arrays.

    private class JsonParser(private val s: String) {
        private var i = 0

        fun parseObject(): Map<String, Any?> {
            expect('{')
            val out = LinkedHashMap<String, Any?>()
            while (true) {
                if (peek() == '}') { i++; break }
                val key = parseString()
                expect(':')
                out[key] = parseValue()
                if (peek() == ',') i++ else { expect('}'); break }
            }
            return out
        }

        private fun parseValue(): Any? = when (peek()) {
            '{' -> parseObject()
            '[' -> parseArray()
            '"' -> parseString()
            't' -> { i += 4; true }
            'f' -> { i += 5; false }
            'n' -> { i += 4; null }
            else -> parseNumber()
        }

        private fun parseArray(): List<Any?> {
            expect('[')
            val out = ArrayList<Any?>()
            while (true) {
                if (peek() == ']') { i++; break }
                out.add(parseValue())
                if (peek() == ',') i++ else { expect(']'); break }
            }
            return out
        }

        private fun parseString(): String {
            expect('"')
            val sb = StringBuilder()
            while (s[i] != '"') {
                if (s[i] == '\\') {
                    i++
                    sb.append(
                        when (s[i]) {
                            'n' -> '\n'; 't' -> '\t'; 'r' -> '\r'; '\\' -> '\\'; '"' -> '"'
                            else -> s[i]
                        }
                    )
                } else sb.append(s[i])
                i++
            }
            i++ // closing quote
            return sb.toString()
        }

        private fun parseNumber(): Double {
            val start = i
            while (i < s.length && (s[i] in "0123456789+-.eE")) i++
            return s.substring(start, i).toDouble()
        }

        private fun peek(): Char {
            while (i < s.length && s[i].isWhitespace()) i++
            return s[i]
        }

        private fun expect(c: Char) {
            while (i < s.length && s[i].isWhitespace()) i++
            check(s[i] == c) { "expected '$c' at $i in JSON" }
            i++
        }
    }

    private data class ChunkRecord(
        val chunk: Int,
        val melInputSamples: Int,
        val melRowsAppended: Int,
        val melRows: List<List<Double>>?,
        val windowRows: List<List<Double>>?,
        val embedding: List<Double>?,
        val confidence: Double?,
    )

    private val records: List<ChunkRecord> by lazy {
        val root = JsonParser(referenceJson).parseObject()
        val pcmSha = root["pcm_sha256"] as String
        assertEquals(pcmSha, sha256(readResource("parity_pcm.bin")), "committed PCM hash")
        val chunks = root["chunk_records"] as List<*>
        chunks.map { raw ->
            val r = raw as Map<String, Any?>
            fun floats(v: Any?): List<List<Double>>? = (v as? List<*>?)?.map { row ->
                (row as List<*>).map { (it as Double) }
            }
            fun flatFloats(v: Any?): List<Double>? = (v as? List<*>?)?.map { (it as Double) }
            ChunkRecord(
                chunk = (r["chunk"] as Double).toInt(),
                melInputSamples = (r["mel_input_samples"] as Double).toInt(),
                melRowsAppended = (r["mel_rows_appended"] as Double).toInt(),
                melRows = floats(r["mel_rows"]),
                windowRows = floats(r["window_rows"]),
                embedding = flatFloats(r["embedding"]),
                confidence = r["classifier_confidence"] as? Double,
            )
        }
    }

    private fun ref(chunk: Int): ChunkRecord = records.first { it.chunk == chunk }

    // ── Comparison helpers ────────────────────────────────────────────────────

    private fun maxAbsDiff(a: FloatArray, b: List<Double>): Float {
        var max = 0f
        for (i in a.indices) {
            val d = kotlin.math.abs(a[i] - b[i].toFloat())
            if (d > max) max = d
        }
        return max
    }

    private fun maxAbsDiff(a: FloatArray, b: FloatArray): Float {
        var max = 0f
        for (i in a.indices) {
            val d = kotlin.math.abs(a[i] - b[i])
            if (d > max) max = d
        }
        return max
    }

    private fun flatten(rows: List<List<Double>>): List<Double> = rows.flatten()

    /**
     * Asserts production [actual] matches reference [expected] within
     * [tolerance].  Same committed ONNX model, CPU on both sides, identical
     * float32 inputs — the tolerance is set from measured run-to-run parity
     * (see the post-fix comparison table in PARITY.md), not chosen to hide
     * structural divergence.
     */
    private fun assertTensorsClose(label: String, actual: FloatArray, expected: List<Double>, tolerance: Float) {
        assertEquals(expected.size, actual.size, "$label size")
        val maxDiff = maxAbsDiff(actual, expected)
        assertTrue(maxDiff <= tolerance, "$label max abs diff $maxDiff > $tolerance")
    }
    /**
     * Runs the production pipeline exactly as the detector hot loop does:
     * [WakeWordMelFeatureState.stage1] (openWakeWord 1760-sample streaming
     * window) → [appendMelRows] ring → [computeEmbedding] →
     * [WakeWordEmbeddingRingState] → [computeClassifierConfidence].  All
     * steps are the extracted production functions the hot loop calls.
     */
    private fun runProductionPipeline(): List<ChunkOutcome> {
        val outcomes = ArrayList<ChunkOutcome>()
        val melState = WakeWordMelFeatureState()
        val melInputPcm = FloatArray(FRAME_SAMPLES + MEL_LEAD_SAMPLES)
        val embedInput4D = FloatArray(MEL_RING_SIZE * MEL_BINS)
        val windowFlat = FloatArray(EMBEDDING_FRAMES * EMBEDDING_DIM)
        val embeddingRing = WakeWordEmbeddingRingState()
        val framePcm = FloatArray(FRAME_SAMPLES)

        for (c in 0 until 50) {
            val chunkStart = c * FRAME_SAMPLES
            for (i in 0 until FRAME_SAMPLES) framePcm[i] = pcm[chunkStart + i].toFloat()

            val melRows = melState.stage1(env, melSession, melInputName, melOutputName, framePcm, melInputPcm)

            var embedding: FloatArray? = null
            var confidence: Float? = null
            var window: FloatArray? = null
            if (melState.filled >= MEL_RING_SIZE) {
                melState.copyStage2Input(embedInput4D)
                embedding = computeEmbedding(env, embedSession, embedInputName, embedOutputName, embedInput4D)
                embeddingRing.append(embedding)
                if (embeddingRing.isWindowComplete) {
                    embeddingRing.copyWindow(windowFlat)
                    window = windowFlat.copyOf()
                    confidence = computeClassifierConfidence(
                        env, classSession, classInputName, classOutputName, windowFlat,
                    )
                }
            }
            outcomes.add(
                ChunkOutcome(
                    chunk = c + 1,
                    inputSamples = melState.lastInputSamples,
                    rowsAppended = melState.lastRowsAppended,
                    melRows = melRows.copyOf(),
                    ring = FloatArray(MEL_RING_SIZE * MEL_BINS).also { melState.copyStage2Input(it) },
                    ringFilled = melState.filled,
                    embedding = embedding?.copyOf(),
                    window = window,
                    confidence = confidence,
                )
            )
        }
        return outcomes
    }

    /**
     * The pre-fix framing (fed 1280 samples per chunk, appended 5 rows with
     * the fixed 5-row drop) — used only by the divergence-guard test to prove
     * the old logic is structurally incompatible with the reference.
     */
    private fun runPreFixPipeline(): List<ChunkOutcome> {
        val outcomes = ArrayList<ChunkOutcome>()
        val melRing = FloatArray(MEL_RING_SIZE * MEL_BINS)
        var melRowsFilled = 0
        val framePcm = FloatArray(FRAME_SAMPLES)

        for (c in 0 until 50) {
            val chunkStart = c * FRAME_SAMPLES
            for (i in 0 until FRAME_SAMPLES) framePcm[i] = pcm[chunkStart + i].toFloat()
            val melRows = computeMelRows(
                env, melSession, melInputName, melOutputName, framePcm, FRAME_SAMPLES, OLD_MEL_ROWS_PER_CHUNK,
            )
            if (melRowsFilled >= MEL_RING_SIZE) {
                melRing.copyInto(melRing, 0, OLD_MEL_ROWS_PER_CHUNK * MEL_BINS, MEL_RING_SIZE * MEL_BINS)
                melRows.copyInto(melRing, (MEL_RING_SIZE - OLD_MEL_ROWS_PER_CHUNK) * MEL_BINS)
                melRowsFilled = MEL_RING_SIZE
            } else {
                val rowsToInsert = minOf(OLD_MEL_ROWS_PER_CHUNK, MEL_RING_SIZE - melRowsFilled)
                melRows.copyInto(melRing, melRowsFilled * MEL_BINS, 0, rowsToInsert * MEL_BINS)
                melRowsFilled += rowsToInsert
            }
            outcomes.add(
                ChunkOutcome(
                    chunk = c + 1,
                    inputSamples = FRAME_SAMPLES,
                    rowsAppended = melRows.size / MEL_BINS,
                    melRows = melRows.copyOf(),
                    ring = melRing.copyOf(),
                    ringFilled = melRowsFilled,
                    embedding = null,
                    window = null,
                    confidence = null,
                )
            )
        }
        return outcomes
    }

    private data class ChunkOutcome(
        val chunk: Int,
        val inputSamples: Int,
        val rowsAppended: Int,
        val melRows: FloatArray,
        val ring: FloatArray,
        val ringFilled: Int,
        val embedding: FloatArray?,
        val window: FloatArray?,
        val confidence: Float?,
    )

    // ── Tests ─────────────────────────────────────────────────────────────────

    @Test
    fun `committed models are the pinned hashes`() {
        val expected = mapOf(
            "melspectrogram.onnx" to "ba2b0e0f8b7b875369a2c89cb13360ff53bac436f2895cced9f479fa65eb176f",
            "embedding_model.onnx" to "70d164290c1d095d1d4ee149bc5e00543250a7316b59f31d056cff7bd3075c1f",
            "hey_jandal.onnx" to "3a920e291662d4b58e10432b5c7f686f00073c45972763d55552200b97f9c4a8",
        )
        for ((name, hash) in expected) {
            val bytes = checkNotNull(javaClass.getResourceAsStream("/models/wakeword/$name"))
                .use { it.readBytes() }
            assertEquals(hash, sha256(bytes), "$name hash")
        }
    }

    @Test
    fun `reference PCM is the committed deterministic stream`() {
        assertEquals(64000, pcm.size)
        assertEquals(50, records.size)
        // The reference JSON embeds the PCM hash; the parser already asserted
        // equality.  Also verify a couple of framing facts that pin the stream:
        assertEquals(1280, ref(1).melInputSamples, "first chunk mel input")
        assertEquals(1760, ref(2).melInputSamples, "steady-state mel input")
        assertEquals(5, ref(1).melRowsAppended)
        assertEquals(8, ref(2).melRowsAppended)
    }

    @Test
    fun `production mel input framing matches the reference per chunk`() {
        val outcomes = runProductionPipeline()
        for (out in outcomes) {
            val r = ref(out.chunk)
            assertEquals(r.melInputSamples, out.inputSamples, "chunk ${out.chunk} mel input length")
            assertEquals(r.melRowsAppended, out.rowsAppended, "chunk ${out.chunk} mel rows appended")
        }
    }

    @Test
    fun `production mel rows match the reference per chunk`() {
        val outcomes = runProductionPipeline()
        for (out in outcomes) {
            val r = ref(out.chunk)
            assertTensorsClose(
                "chunk ${out.chunk} mel rows",
                out.melRows, flatten(checkNotNull(r.melRows)), MEL_ROW_TOLERANCE,
            )
        }
    }

    @Test
    fun `production rolling mel context matches the reference from chunk 10`() {
        // From chunk 10 the reference window is pure real rows (the 76-row
        // ones pre-fill is fully evicted); before that the reference window is
        // ones-contaminated and has no production counterpart.
        val outcomes = runProductionPipeline()
        for (out in outcomes) {
            if (out.chunk < 10) continue
            val r = ref(out.chunk)
            assertTensorsClose(
                "chunk ${out.chunk} mel ring window",
                out.ring, flatten(checkNotNull(r.windowRows)), MEL_ROW_TOLERANCE,
            )
        }
    }

    @Test
    fun `production embeddings match the reference per chunk`() {
        val outcomes = runProductionPipeline()
        for (out in outcomes) {
            if (out.embedding == null) continue
            val r = ref(out.chunk)
            assertEquals(r.embedding != null, out.embedding != null, "chunk ${out.chunk} embedding present")
            assertTensorsClose(
                "chunk ${out.chunk} embedding",
                out.embedding, checkNotNull(r.embedding), EMBEDDING_TOLERANCE,
            )
        }
    }

    @Test
    fun `production classifier windows and confidence match the reference`() {
        val outcomes = runProductionPipeline()
        var compared = 0
        for (out in outcomes) {
            if (out.confidence == null) continue
            val r = ref(out.chunk)
            assertEquals(r.confidence != null, out.confidence != null, "chunk ${out.chunk} score present")
            // The reference confidence is computed over the same last-16
            // embeddings (chunks out.chunk-15..out.chunk); the window content
            // is verified through the per-chunk embedding comparison above, so
            // here we compare the end-to-end scores.
            val maxDiff = kotlin.math.abs(out.confidence - r.confidence!!.toFloat())
            assertTrue(maxDiff <= CONFIDENCE_TOLERANCE, "chunk ${out.chunk} confidence diff $maxDiff")
            compared++
        }
        assertTrue(compared >= 26, "expected >= 26 compared windows, got $compared")
    }

    @Test
    fun `pre-fix 5-row framing diverges from the reference at chunk 2`() {
        // Guards the regression: the old production framing (1280 samples, 5
        // rows per chunk) must never silently return.  With it, chunk 2
        // appends 5 rows instead of the reference 8 and every later window is
        // structurally different.
        val outcomes = runPreFixPipeline()
        assertEquals(1280, outcomes[0].inputSamples)
        assertEquals(5, outcomes[0].rowsAppended)
        assertEquals(1280, outcomes[1].inputSamples, "pre-fix chunk 2 input")
        assertEquals(5, outcomes[1].rowsAppended, "pre-fix chunk 2 rows")
        assertTrue(
            outcomes[1].rowsAppended != ref(2).melRowsAppended,
            "pre-fix framing must diverge at chunk 2 (5 vs 8 rows)",
        )
    }

    @Test
    fun `production embedding cadence is one embedding per chunk from chunk 10`() {
        val outcomes = runProductionPipeline()
        for (out in outcomes) {
            assertEquals(out.chunk >= 10, out.embedding != null, "chunk ${out.chunk} embedding cadence")
        }
        // Ring completion: chunk 10 is the first chunk with >= 76 mel rows.
        assertEquals(76, outcomes[9].ringFilled, "chunk 10 ring filled")
    }

    @Test
    fun `mel feature state resets cleanly at a generation boundary`() {
        // The detector allocates a fresh WakeWordMelFeatureState per
        // generation; reset() must return it to the cold-start state so a new
        // generation never inherits the previous generation's mel rows.
        val first = runProductionPipeline()
        val melState = WakeWordMelFeatureState()
        val melInputPcm = FloatArray(FRAME_SAMPLES + MEL_LEAD_SAMPLES)
        val framePcm = FloatArray(FRAME_SAMPLES)
        for (c in 0 until 25) {
            for (i in 0 until FRAME_SAMPLES) framePcm[i] = pcm[c * FRAME_SAMPLES + i].toFloat()
            melState.stage1(env, melSession, melInputName, melOutputName, framePcm, melInputPcm)
        }
        val before = melState.filled
        assertTrue(before > 0, "state accumulated rows before reset")
        melState.reset()
        assertEquals(0, melState.filled, "reset clears the ring")
        assertEquals(0, melState.lastInputSamples, "reset clears framing")
        // A fresh run after reset reproduces the cold-start trajectory exactly.
        val second = runProductionPipeline()
        for (i in 0 until 50) {
            assertEquals(first[i].rowsAppended, second[i].rowsAppended, "chunk ${i + 1} rows")
            assertEquals(first[i].confidence, second[i].confidence, "chunk ${i + 1} confidence")
        }
    }

    @Test
    fun `mel feature state persists across calls without flushing (gate-resume safe)`() {
        // The silence gate never touches the mel state: Stage 1 keeps running
        // every frame while gated, and the ring is per-generation, not
        // per-gate-episode (#1432 resume semantics).  A continuous 50-chunk
        // run must therefore be identical to a run split by an arbitrary
        // "gate" boundary with no reset.
        val continuous = runProductionPipeline()
        val melState = WakeWordMelFeatureState()
        val melInputPcm = FloatArray(FRAME_SAMPLES + MEL_LEAD_SAMPLES)
        val framePcm = FloatArray(FRAME_SAMPLES)
        val split = ArrayList<ChunkOutcome>()
        for (c in 0 until 50) {
            for (i in 0 until FRAME_SAMPLES) framePcm[i] = pcm[c * FRAME_SAMPLES + i].toFloat()
            melState.stage1(env, melSession, melInputName, melOutputName, framePcm, melInputPcm)
            split.add(
                ChunkOutcome(
                    chunk = c + 1,
                    inputSamples = melState.lastInputSamples,
                    rowsAppended = melState.lastRowsAppended,
                    melRows = FloatArray(0),
                    ring = FloatArray(MEL_RING_SIZE * MEL_BINS).also { melState.copyStage2Input(it) },
                    ringFilled = melState.filled,
                    embedding = null,
                    window = null,
                    confidence = null,
                )
            )
            // Simulated gate episode boundary: no state mutation allowed.
            if (c == 24) {
                assertEquals(76, melState.filled, "ring full at the simulated gate boundary")
            }
        }
        for (c in 0 until 50) {
            assertEquals(continuous[c].ringFilled, split[c].ringFilled, "chunk ${c + 1} filled")
            assertEquals(
                maxAbsDiff(continuous[c].ring, split[c].ring), 0f,
                "chunk ${c + 1} ring content preserved across calls",
            )
        }
    }

    @Test
    fun `repeated production execution is deterministic bit-exactly`() {
        val a = runProductionPipeline()
        val b = runProductionPipeline()
        for (c in 0 until 50) {
            assertEquals(0f, maxAbsDiff(a[c].melRows, b[c].melRows), "chunk ${c + 1} mel rows")
            assertEquals(0f, maxAbsDiff(a[c].ring, b[c].ring), "chunk ${c + 1} ring")
            if (a[c].embedding != null) {
                assertEquals(0f, maxAbsDiff(a[c].embedding!!, b[c].embedding!!), "chunk ${c + 1} embedding")
            }
            assertEquals(a[c].confidence, b[c].confidence, "chunk ${c + 1} confidence")
        }
    }

    private companion object {
        // Pre-fix constant retained only to demonstrate the old framing.
        const val OLD_MEL_ROWS_PER_CHUNK = 5

        // Measured parity tolerances (same model, CPU both sides, float32):
        // the post-fix production pipeline reproduces the Python reference
        // bit-exactly on the committed stream (measured max abs diff 0.0 for
        // mel rows, ring windows, embeddings and confidence across all 50
        // chunks).  The tolerance band is pure headroom for cross-runtime
        // float jitter on other hosts, not a band hiding structural
        // divergence (structural divergence measures ~5-18 here).
        const val MEL_ROW_TOLERANCE = 1e-4f
        const val EMBEDDING_TOLERANCE = 1e-4f
        const val CONFIDENCE_TOLERANCE = 1e-5f
    }
}
